os: linux
dist: xenial

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
    include:
        - php: 7.4
          env: COMPOSER_VERSION="1.10.*"
        - php: 7.4
          env: COMPOSER_VERSION="2.0.*"
        - php: 7.4
          env: COMPOSER_VERSION="2.1.*"
        - php: 7.4
          env: COMPOSER_VERSION="2.2.*"
        - php: 7.4
          env: COMPOSER_VERSION="2.3.*"
        - php: 7.4
          env: COMPOSER_VERSION="2.4.*"
        - php: 7.4
          env: COMPOSER_VERSION="2.5.*"
        - php: 8.0
          env: COMPOSER_VERSION="1.10.*"
        - php: 8.0
          env: COMPOSER_VERSION="2.0.*"
        - php: 8.0
          env: COMPOSER_VERSION="2.1.*"
        - php: 8.0
          env: COMPOSER_VERSION="2.2.*"
        - php: 8.0
          env: COMPOSER_VERSION="2.3.*"
        - php: 8.0
          env: COMPOSER_VERSION="2.4.*"
        - php: 8.0
          env: COMPOSER_VERSION="2.5.*"
        - php: 8.1
          env: COMPOSER_VERSION="1.10.*"
        - php: 8.1
          env: COMPOSER_VERSION="2.0.*"
        - php: 8.1
          env: COMPOSER_VERSION="2.1.*"
        - php: 8.1
          env: COMPOSER_VERSION="2.2.*"
        - php: 8.1
          env: COMPOSER_VERSION="2.3.*"
        - php: 8.1
          env: COMPOSER_VERSION="2.4.*"
        - php: 8.1
          env: COMPOSER_VERSION="2.5.*"
        - php: 8.2
          env: COMPOSER_VERSION="1.10.*"
        - php: 8.2
          env: COMPOSER_VERSION="2.0.*"
        - php: 8.2
          env: COMPOSER_VERSION="2.1.*"
        - php: 8.2
          env: COMPOSER_VERSION="2.2.*"
        - php: 8.2
          env: COMPOSER_VERSION="2.3.*"
        - php: 8.2
          env: COMPOSER_VERSION="2.4.*"
        - php: 8.2
          env: COMPOSER_VERSION="2.5.*"
        - php: nightly
          env: COMPOSER_VERSION="1.10.*"
        - php: nightly
          env: COMPOSER_VERSION="2.0.*"
        - php: nightly
          env: COMPOSER_VERSION="2.1.*"
        - php: nightly
          env: COMPOSER_VERSION="2.2.*"
        - php: nightly
          env: COMPOSER_VERSION="2.3.*"
        - php: nightly
          env: COMPOSER_VERSION="2.4.*"
        - php: nightly
          env: COMPOSER_VERSION="2.5.*"

    allow_failures:
        - php: nightly

    fast_finish: true

before_script:
    - |
      if [ "$COMPOSER_VERSION" == "" ]; then composer install; fi;
      if [ "$COMPOSER_VERSION" != "" ]; then composer require --dev --with-all-dependencies "composer/composer:${COMPOSER_VERSION}"; fi;
      composer require --dev --with-all-dependencies phpunit/phpunit:"^9.5.0" php-coveralls/php-coveralls:"^2.4.0"
      mkdir -p ./build/logs

script:
    - |
      vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_success:
    - |
      if [ "$TRAVIS_PHP_VERSION" != nightly ]; then php vendor/bin/php-coveralls -v; fi

notifications:
    email: false
