---
on:
  - pull_request
  - push

name: quality

permissions:
  contents: read

jobs:
  quality:
    uses: php-forge/actions/.github/workflows/quality.yml@a574dbe95fc370db1b7b5ea546cd5ff5b70304d6 # v3.0.0
    permissions:
      contents: read
    with:
      codespell-config: .github/linters/.codespellrc
      editorconfig-checker-config: .github/linters/.editorconfig-checker.json
      markdownlint-config: .github/linters/.markdown-lint.yml
      prettier-config: .prettierrc.json
      prettier-ignore-path: .prettierignore
      yamllint-targets: .github
